/** @type {import('next').NextConfig} */
const nextConfig = {
  reactStrictMode: true,
  transpilePackages: [
    "antd",
    "@ant-design/icons",
    "@ant-design/icons-svg",
    "@rc-component/util",
    "@rc-component/trigger",
    "@rc-component/portal",
    "@rc-component/mini-decimal",
    "@rc-component/tour",
    "@rc-component/qrcode",
    "@rc-component/color-picker",
    "@rc-component/mutate-observer",
    "rc-util",
    "rc-pagination",
    "rc-picker",
    "rc-notification",
    "rc-tooltip",
    "rc-tree",
    "rc-table",
    "rc-input",
    "rc-textarea",
    "rc-select",
    "rc-cascader",
    "rc-checkbox",
    "rc-collapse",
    "rc-dialog",
    "rc-drawer",
    "rc-dropdown",
    "rc-field-form",
    "rc-image",
    "rc-input-number",
    "rc-mentions",
    "rc-menu",
    "rc-motion",
    "rc-progress",
    "rc-rate",
    "rc-resize-observer",
    "rc-segmented",
    "rc-slider",
    "rc-steps",
    "rc-switch",
    "rc-tabs",
    "rc-upload",
    "rc-virtual-list",
  ],
};

module.exports = nextConfig;
